// Auto-extracted from index.html on 2026-05-05T18:36:56.267564Z
// All dashboard content lives here. Edit this file (not index.html) on refresh.

window.DASHBOARD_DATA = {
  lastUpdated: "2026-06-08T16:00:00.000Z",
  ticker: [
    "🌎 Mexico face South Africa to open WC26 at the Estadio Azteca on Thu Jun 11, 3PM ET — the Azteca becomes the first venue ever to host three World Cup openers (Jun 8)",
    "🦁 England edge New Zealand 1-0 in their Miami warm-up and face Costa Rica on Jun 10 before basing in Kansas City (Jun 7)",
    "🇩🇪 Manuel Neuer, 40, returns in goal for Germany's fifth-World-Cup campaign — they open vs debutants Curaçao on Jun 14 (Jun 6)",
    "🇨🇦 Canada lose Moïse Bombito to injury days before their Jun 12 opener vs Bosnia at BMO Field — Marsch reshuffles the back line (Jun 7)",
    "🇺🇸 USMNT open Jun 12 vs Paraguay at SoFi in Group D, alongside Australia & Türkiye (Jun 8)",
    "🐐 Messi progressing from hamstring fatigue, in line to feature in Argentina's final warm-up vs Honduras at Kyle Field (Jun 7)",
    "🎉 FIFA Fan Festivals open across host cities — LA Jun 11–14, Boston Jun 12–27, plus a NY/NJ road tour (Jun 8)",
    "🇨🇦 Canada name their final 26 today — Marsch locks the host roster ahead of the June 12 opener vs Bosnia at BMO (May 29)",
    "🇺🇸 USMNT final 26 revealed at Pier 17 NYC — Pochettino's World Cup roster is locked (May 26)",
    "🇧🇷 Neymar suffers a grade-2 calf tear — out of Brazil's warm-ups vs Panama & Egypt, cleared in 2-3 weeks (May 28)",
    "🌎 Netherlands & South Africa drop final squads; all 48 rosters lock June 1 (May 27)",
    "🎟️ Dallas Fan Fest concerts on sale today from $26; LA Fan Fest GA is just $10, kids free (May 29)",
    "💸 Cheapest FIFA tickets still ~$380 as some resale Final seats hit $2M apiece (May 28)",
    "🏟️ Arrowhead becomes 'Kansas City Stadium' for the WC — 6 games, kickoff in under 3 weeks (May 28)",
    "🇧🇦 Bosnia first to announce full 26 — Dzeko, 40, leads the Dragons back to the WC (May 11)",
    "🇦🇷 Scaloni's 55 named: Messi in, Di María and Dybala OUT — r/soccer in flames (May 11)",
    "🇧🇷 Ancelotti recalls Neymar to Brazil's 55; Estêvão ruled out injured (May 11)",
    "🇩🇪 Nagelsmann postpones Germany's final-26 reveal from May 12 to May 21 (May 12)",
    "🇨🇦 Canada Soccer keeps preliminary list secret; Davies hamstring race continues (May 11)",
    "🇨🇳 FIFA-CCTV deal still dead 5 weeks out — China blackout looms over 2B+ fans (May 11)",
  ],
  news: [
    {
      "id": "n144",
      "headline": "🌎 Azteca Makes History: Mexico v South Africa Opens WC26 on Thursday",
      "source": "FIFA",
      "timestamp": "2026-06-08T15:00:00Z",
      "summary": "The tournament kicks off Thursday June 11 when hosts Mexico face South Africa at the Estadio Azteca (3PM ET) — the first venue ever to stage three World Cup openers, after 1970 and 1986. With 80,000+ inside and a global audience tuning in, this is the single biggest reactive window of the group stage: opening-whistle, anthem and first-goal moments will spike everywhere at once. Have Mexico and 'opening day of the World Cup' creative cued to ship the instant the ball rolls 🇲🇽",
      "url": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/estadio-azteca-mexico-city-host-opening-match-world-cup-2026",
      "tag": "Global"
    },
    {
      "id": "n143",
      "headline": "🦁 England Beat New Zealand 1-0 in Miami Warm-Up; Costa Rica Next Before KC Base",
      "source": "ESPN",
      "timestamp": "2026-06-07T12:00:00Z",
      "summary": "Thomas Tuchel's England edged New Zealand 1-0 in their first pre-tournament friendly in south Florida on June 6, with the late-arriving Arsenal contingent (Rice, Saka, Madueke, Eze) still to integrate after the Champions League final. A second tune-up against Costa Rica follows on June 10 before the squad settles into its tournament base in Kansas City on June 13. Heat acclimatization is the quiet story — expect 'Three Lions in the sun' angles and Kane-captaincy content from UK fans 🦁",
      "url": "https://www.espn.com/soccer/story/_/id/48870079/world-cup-2026-england-pre-tournament-friendlies-do-play-dates-venues-how-watch",
      "tag": "UK"
    },
    {
      "id": "n142",
      "headline": "🇩🇪 Neuer, 40, Returns in Goal as Germany Open Against Debutants Curaçao",
      "source": "FIFA",
      "timestamp": "2026-06-06T11:00:00Z",
      "summary": "Julian Nagelsmann's headline call is Manuel Neuer — back at 40 for a record-equalling fifth World Cup and named first choice ahead of Baumann and Nübel. Germany open June 14 against Curaçao, the smallest nation ever to reach a World Cup, instantly setting up a David-vs-Goliath storyline. With Musiala, Wirtz and Kimmich around the veteran keeper, German feeds are torn between 'respect the legend' nostalgia and 'why Neuer at 40' debate — both are strong reactive lanes 🧤",
      "url": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/germany-squad-neuer-nagelsmann-named",
      "tag": "Germany"
    },
    {
      "id": "n141",
      "headline": "🇨🇦 Canada Lose Bombito to Injury Days Before the Opener — Marsch Reshuffles",
      "source": "Yahoo Sports",
      "timestamp": "2026-06-07T16:00:00Z",
      "summary": "Host nation Canada were dealt a late blow as defender Moïse Bombito was ruled out of World Cup consideration with a leg injury that hasn't healed in time, forcing Jesse Marsch into a back-line reshuffle just days before the June 12 opener vs Bosnia & Herzegovina at BMO Field. As one of three hosts, Canada carry home-soil pressure and a passionate Toronto crowd — keep contingency creative ready for both the injury-news cycle and the opening-day hype 🍁",
      "url": "https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-updates-injuries-squads-storylines-as-the-tournament-looms-200000776.html",
      "tag": "Canada"
    },
    {
      "id": "n140",
      "headline": "🇺🇸 USMNT Open June 12 vs Paraguay at SoFi — Group D With Australia & Türkiye",
      "source": "ESPN",
      "timestamp": "2026-06-08T14:00:00Z",
      "summary": "The host United States begin their campaign June 12 against Paraguay at SoFi Stadium in Inglewood (9PM ET), drawn into Group D alongside Australia and Türkiye. Pochettino's home-soil side carries the biggest domestic spotlight of the tournament, and the LA opening festivities (Fan Festival June 11–14) wrap the match in a citywide moment. This is the marquee US reactive window — have USMNT and 'football comes home to America' creative locked 🇺🇸",
      "url": "https://www.espn.com/soccer/story/_/id/48939282/2026-fifa-world-cup-fixtures-results-match-schedule-group-stage-knockout-rounds-bracket",
      "tag": "USA"
    },
    {
      "id": "n139",
      "headline": "🐐 Messi Progressing From Hamstring Fatigue, in Line for Honduras Warm-Up",
      "source": "Yahoo Sports",
      "timestamp": "2026-06-07T10:00:00Z",
      "summary": "Argentina boss Lionel Scaloni says Lionel Messi — managing left-hamstring fatigue since late May — is progressing well and could feature in the final warm-up against Honduras at Kyle Field, Texas. With this set to be Messi's record sixth and final World Cup, every fitness update moves the needle and the 'Last Dance' narrative is already dominant. Stay ready to react to his first appearance, but keep the tone about the football, not the GOAT debate 🐐",
      "url": "https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-updates-injuries-squads-storylines-as-the-tournament-looms-200000776.html",
      "tag": "Global"
    },
    {
      "id": "n138",
      "headline": "🎉 FIFA Fan Festivals Open Across Host Cities as Kickoff Nears",
      "source": "FIFA",
      "timestamp": "2026-06-08T13:00:00Z",
      "summary": "The official FIFA Fan Festivals are switching on across North America: Los Angeles runs June 11–14 with live matches, food and music tied to the US opener, Boston's festival runs June 12–27 with a local cultural showcase, and a 'Skyline to Shoreline' road tour brings the tournament to NY/NJ communities. These free fan zones are where culture, food and football collide — prime territory for on-the-ground, city-tagged content that isn't just match reactions 🥳",
      "url": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/fifa-fan-festival",
      "tag": "USA"
    },
    {
      "id": "n137",
      "headline": "🌡️ Summer Heat Becomes a Tournament Storyline as Teams Acclimatize",
      "source": "Yahoo Sports",
      "timestamp": "2026-06-06T18:00:00Z",
      "summary": "With matches across a North American summer, heat and humidity are shaping preparation: England based their warm-ups in south Florida specifically to acclimatize, and afternoon kickoffs in cities like Mexico City, Dallas and Monterrey raise real player-welfare questions. Expect water-break tactics, lineup rotation and 'is it too hot for football' debate to recur all tournament — a steady, cross-market angle that pairs well with hydration and endurance creative ☀️",
      "url": "https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-updates-injuries-squads-storylines-as-the-tournament-looms-200000776.html",
      "tag": "Macro"
    },
    {
      "id": "n136",
      "headline": "🇺🇸 Pochettino Locks USMNT's Final 26 at Pier 17 — Host Nation's World Cup Roster Is Set",
      "source": "ESPN",
      "timestamp": "2026-05-26T19:00:00Z",
      "summary": "Mauricio Pochettino unveiled the United States' final 26-man World Cup squad at a Pier 17 event in New York on May 26 — the last major reveal before FIFA's June 1 lock. As hosts, the USMNT carry the home-soil spotlight, and Pochettino's selection (and his omissions) immediately set the tone for the opening narrative. Expect creator feeds to swing between hype reels and snub debates over the next 72 hours 🇺🇸",
      "url": "https://www.espn.com/soccer/story/_/id/48757621/2026-world-cup-squad-lists-players-announced-all-48-teams",
      "tag": "USA"
    },
    {
      "id": "n137",
      "headline": "🇨🇦 Canada Name Their Final 26 Today — Host Roster Set for the June 12 Opener",
      "source": "Yahoo Sports",
      "timestamp": "2026-05-29T14:00:00Z",
      "summary": "Canada confirm their final 26-man squad today, May 29 — the same day as Egypt and just ahead of FIFA's June 1 deadline. Jesse Marsch's group builds toward the June 12 opener vs Bosnia & Herzegovina at BMO Field in Toronto, with Alphonso Davies' fitness the headline storyline for the co-hosts. A clean moment for Canada-market reactive content: 'this is our team' energy 🇨🇦",
      "url": "https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-tracker-squad-announcements-injuries-key-storylines-and-latest-updates-200000056.html",
      "tag": "Canada"
    },
    {
      "id": "n138",
      "headline": "🇧🇷 Neymar Suffers Grade-2 Calf Tear — Brazil Opener Now a Race Against the Clock",
      "source": "Yahoo Sports",
      "timestamp": "2026-05-28T16:00:00Z",
      "summary": "Brazil team doctor Rodrigo Lasmar confirmed Neymar suffered a grade-2 calf injury — 'not just swelling' — ruling the 34-year-old out of the Seleção's warm-up matches against Panama and Egypt and putting his availability for the opener in doubt. 'He is expected to be cleared in two to three weeks,' Lasmar said. Latam social is split between 'protect him for the knockouts' and full-blown fatalism 🇧🇷",
      "url": "https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-tracker-squad-announcements-injuries-key-storylines-and-latest-updates-200000056.html",
      "tag": "Brazil"
    },
    {
      "id": "n139",
      "headline": "🌎 Netherlands & South Africa Reveal Final Squads — All 48 Rosters Lock June 1",
      "source": "Sky Sports",
      "timestamp": "2026-05-27T18:00:00Z",
      "summary": "The Netherlands and South Africa both confirmed their final 26-man squads on May 27, joining Brazil (May 18), Germany (May 21) and USA and Morocco (May 26) on the board. With Canada and Egypt revealing on May 29, the picture is nearly complete — but FIFA rules mean nothing is final until June 1, so injury-forced swaps remain in play. Squad-reveal graphics are the dominant content format this week 🌎",
      "url": "https://www.skysports.com/football/news/11095/13543070/world-cup-2026-squad-lists-england-scotland-brazil-usa-spain-france-germany-netherlands-argentina-portugal-and-more",
      "tag": "Global"
    },
    {
      "id": "n140",
      "headline": "💸 Cheapest WC Tickets Still ~$380 as Resale Finals Hit $2M — Pricing Backlash Builds",
      "source": "Al Jazeera",
      "timestamp": "2026-05-28T12:00:00Z",
      "summary": "With under three weeks to kickoff, the cheapest tickets on FIFA's official site still start around $380, while unregulated US resale and dynamic pricing have pushed some Final seats as high as $2M apiece. The affordability gap is now the defining off-pitch story of the tournament and is driving fans toward free and low-cost alternatives. Brand-safe angle: lean into access and community, not the price outrage itself 💸",
      "url": "https://www.aljazeera.com/sports/2026/5/11/fan-festivals-panini-tickets-what-are-fifa-world-cup-fans-talking-about",
      "tag": "Macro"
    },
    {
      "id": "n141",
      "headline": "🎉 Fan Fests Become the Affordable World Cup — LA GA $10, Dallas Concerts From $26",
      "source": "CBS News Texas",
      "timestamp": "2026-05-29T15:00:00Z",
      "summary": "As ticket prices climb, host-city FIFA Fan Festivals are emerging as the accessible way to experience WC2026. Los Angeles set GA at just $10 (kids under 12 free); Dallas opens free but ticketed its three Fair Park concerts from $26, on sale today, May 29. Atlanta, Philadelphia, Kansas City, Mexico City and Vancouver are among cities offering free general admission. This is the feel-good, shareable counter-narrative to the ticket story 🎉",
      "url": "https://www.cbsnews.com/texas/news/2026-world-cup-dallas-fan-fest-music-acts/",
      "tag": "USA"
    }
  ],
  matches: [
    {
      id: "m1",
      date: "2026-06-11",
      kickoff: "3:00 PM ET",
      stage: "Group A",
      home: {
        name: "Mexico",
        code: "MEX",
        flag: "🇲🇽",
      },
      away: {
        name: "South Africa",
        code: "RSA",
        flag: "🇿🇦",
      },
      venue: "Estadio Azteca, Mexico City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m2",
      date: "2026-06-11",
      kickoff: "10:00 PM ET",
      stage: "Group A",
      home: {
        name: "South Korea",
        code: "KOR",
        flag: "🇰🇷",
      },
      away: {
        name: "Czechia",
        code: "CZE",
        flag: "🇨🇿",
      },
      venue: "Estadio Akron, Guadalajara",
      status: "upcoming",
      score: null,
    },
    {
      id: "m3",
      date: "2026-06-18",
      kickoff: "12:00 PM ET",
      stage: "Group A",
      home: {
        name: "Czechia",
        code: "CZE",
        flag: "🇨🇿",
      },
      away: {
        name: "South Africa",
        code: "RSA",
        flag: "🇿🇦",
      },
      venue: "Mercedes-Benz Stadium, Atlanta",
      status: "upcoming",
      score: null,
    },
    {
      id: "m4",
      date: "2026-06-18",
      kickoff: "9:00 PM ET",
      stage: "Group A",
      home: {
        name: "Mexico",
        code: "MEX",
        flag: "🇲🇽",
      },
      away: {
        name: "South Korea",
        code: "KOR",
        flag: "🇰🇷",
      },
      venue: "Estadio Akron, Guadalajara",
      status: "upcoming",
      score: null,
    },
    {
      id: "m5",
      date: "2026-06-24",
      kickoff: "9:00 PM ET",
      stage: "Group A",
      home: {
        name: "Czechia",
        code: "CZE",
        flag: "🇨🇿",
      },
      away: {
        name: "Mexico",
        code: "MEX",
        flag: "🇲🇽",
      },
      venue: "Estadio Azteca, Mexico City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m6",
      date: "2026-06-24",
      kickoff: "9:00 PM ET",
      stage: "Group A",
      home: {
        name: "South Africa",
        code: "RSA",
        flag: "🇿🇦",
      },
      away: {
        name: "South Korea",
        code: "KOR",
        flag: "🇰🇷",
      },
      venue: "Estadio BBVA, Monterrey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m7",
      date: "2026-06-12",
      kickoff: "3:00 PM ET",
      stage: "Group B",
      home: {
        name: "Canada",
        code: "CAN",
        flag: "🇨🇦",
      },
      away: {
        name: "Bosnia & Herzegovina",
        code: "BIH",
        flag: "🇧🇦",
      },
      venue: "BMO Field, Toronto",
      status: "upcoming",
      score: null,
    },
    {
      id: "m8",
      date: "2026-06-13",
      kickoff: "3:00 PM ET",
      stage: "Group B",
      home: {
        name: "Qatar",
        code: "QAT",
        flag: "🇶🇦",
      },
      away: {
        name: "Switzerland",
        code: "SUI",
        flag: "🇨🇭",
      },
      venue: "Levi's Stadium, San Francisco",
      status: "upcoming",
      score: null,
    },
    {
      id: "m9",
      date: "2026-06-18",
      kickoff: "3:00 PM ET",
      stage: "Group B",
      home: {
        name: "Switzerland",
        code: "SUI",
        flag: "🇨🇭",
      },
      away: {
        name: "Bosnia & Herzegovina",
        code: "BIH",
        flag: "🇧🇦",
      },
      venue: "SoFi Stadium, Los Angeles",
      status: "upcoming",
      score: null,
    },
    {
      id: "m10",
      date: "2026-06-18",
      kickoff: "6:00 PM ET",
      stage: "Group B",
      home: {
        name: "Canada",
        code: "CAN",
        flag: "🇨🇦",
      },
      away: {
        name: "Qatar",
        code: "QAT",
        flag: "🇶🇦",
      },
      venue: "BC Place, Vancouver",
      status: "upcoming",
      score: null,
    },
    {
      id: "m11",
      date: "2026-06-24",
      kickoff: "3:00 PM ET",
      stage: "Group B",
      home: {
        name: "Switzerland",
        code: "SUI",
        flag: "🇨🇭",
      },
      away: {
        name: "Canada",
        code: "CAN",
        flag: "🇨🇦",
      },
      venue: "BC Place, Vancouver",
      status: "upcoming",
      score: null,
    },
    {
      id: "m12",
      date: "2026-06-24",
      kickoff: "3:00 PM ET",
      stage: "Group B",
      home: {
        name: "Bosnia & Herzegovina",
        code: "BIH",
        flag: "🇧🇦",
      },
      away: {
        name: "Qatar",
        code: "QAT",
        flag: "🇶🇦",
      },
      venue: "Lumen Field, Seattle",
      status: "upcoming",
      score: null,
    },
    {
      id: "m13",
      date: "2026-06-13",
      kickoff: "6:00 PM ET",
      stage: "Group C",
      home: {
        name: "Brazil",
        code: "BRA",
        flag: "🇧🇷",
      },
      away: {
        name: "Morocco",
        code: "MAR",
        flag: "🇲🇦",
      },
      venue: "MetLife Stadium, New Jersey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m14",
      date: "2026-06-13",
      kickoff: "9:00 PM ET",
      stage: "Group C",
      home: {
        name: "Haiti",
        code: "HAI",
        flag: "🇭🇹",
      },
      away: {
        name: "Scotland",
        code: "SCO",
        flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      },
      venue: "Gillette Stadium, Boston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m15",
      date: "2026-06-19",
      kickoff: "6:00 PM ET",
      stage: "Group C",
      home: {
        name: "Scotland",
        code: "SCO",
        flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      },
      away: {
        name: "Morocco",
        code: "MAR",
        flag: "🇲🇦",
      },
      venue: "Gillette Stadium, Boston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m16",
      date: "2026-06-19",
      kickoff: "9:00 PM ET",
      stage: "Group C",
      home: {
        name: "Brazil",
        code: "BRA",
        flag: "🇧🇷",
      },
      away: {
        name: "Haiti",
        code: "HAI",
        flag: "🇭🇹",
      },
      venue: "Lincoln Financial Field, Philadelphia",
      status: "upcoming",
      score: null,
    },
    {
      id: "m17",
      date: "2026-06-24",
      kickoff: "6:00 PM ET",
      stage: "Group C",
      home: {
        name: "Scotland",
        code: "SCO",
        flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      },
      away: {
        name: "Brazil",
        code: "BRA",
        flag: "🇧🇷",
      },
      venue: "Hard Rock Stadium, Miami",
      status: "upcoming",
      score: null,
    },
    {
      id: "m18",
      date: "2026-06-24",
      kickoff: "6:00 PM ET",
      stage: "Group C",
      home: {
        name: "Morocco",
        code: "MAR",
        flag: "🇲🇦",
      },
      away: {
        name: "Haiti",
        code: "HAI",
        flag: "🇭🇹",
      },
      venue: "Mercedes-Benz Stadium, Atlanta",
      status: "upcoming",
      score: null,
    },
    {
      id: "m19",
      date: "2026-06-12",
      kickoff: "9:00 PM ET",
      stage: "Group D",
      home: {
        name: "USA",
        code: "USA",
        flag: "🇺🇸",
      },
      away: {
        name: "Paraguay",
        code: "PAR",
        flag: "🇵🇾",
      },
      venue: "SoFi Stadium, Los Angeles",
      status: "upcoming",
      score: null,
    },
    {
      id: "m20",
      date: "2026-06-13",
      kickoff: "12:00 AM ET",
      stage: "Group D",
      home: {
        name: "Australia",
        code: "AUS",
        flag: "🇦🇺",
      },
      away: {
        name: "Türkiye",
        code: "TUR",
        flag: "🇹🇷",
      },
      venue: "BC Place, Vancouver",
      status: "upcoming",
      score: null,
    },
    {
      id: "m21",
      date: "2026-06-19",
      kickoff: "3:00 PM ET",
      stage: "Group D",
      home: {
        name: "USA",
        code: "USA",
        flag: "🇺🇸",
      },
      away: {
        name: "Australia",
        code: "AUS",
        flag: "🇦🇺",
      },
      venue: "Lumen Field, Seattle",
      status: "upcoming",
      score: null,
    },
    {
      id: "m22",
      date: "2026-06-19",
      kickoff: "12:00 AM ET",
      stage: "Group D",
      home: {
        name: "Türkiye",
        code: "TUR",
        flag: "🇹🇷",
      },
      away: {
        name: "Paraguay",
        code: "PAR",
        flag: "🇵🇾",
      },
      venue: "Levi's Stadium, San Francisco",
      status: "upcoming",
      score: null,
    },
    {
      id: "m23",
      date: "2026-06-25",
      kickoff: "10:00 PM ET",
      stage: "Group D",
      home: {
        name: "Türkiye",
        code: "TUR",
        flag: "🇹🇷",
      },
      away: {
        name: "USA",
        code: "USA",
        flag: "🇺🇸",
      },
      venue: "SoFi Stadium, Los Angeles",
      status: "upcoming",
      score: null,
    },
    {
      id: "m24",
      date: "2026-06-25",
      kickoff: "10:00 PM ET",
      stage: "Group D",
      home: {
        name: "Paraguay",
        code: "PAR",
        flag: "🇵🇾",
      },
      away: {
        name: "Australia",
        code: "AUS",
        flag: "🇦🇺",
      },
      venue: "Levi's Stadium, San Francisco",
      status: "upcoming",
      score: null,
    },
    {
      id: "m25",
      date: "2026-06-14",
      kickoff: "1:00 PM ET",
      stage: "Group E",
      home: {
        name: "Germany",
        code: "GER",
        flag: "🇩🇪",
      },
      away: {
        name: "Curaçao",
        code: "CUW",
        flag: "🇨🇼",
      },
      venue: "NRG Stadium, Houston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m26",
      date: "2026-06-14",
      kickoff: "7:00 PM ET",
      stage: "Group E",
      home: {
        name: "Ivory Coast",
        code: "CIV",
        flag: "🇨🇮",
      },
      away: {
        name: "Ecuador",
        code: "ECU",
        flag: "🇪🇨",
      },
      venue: "Lincoln Financial Field, Philadelphia",
      status: "upcoming",
      score: null,
    },
    {
      id: "m27",
      date: "2026-06-20",
      kickoff: "4:00 PM ET",
      stage: "Group E",
      home: {
        name: "Germany",
        code: "GER",
        flag: "🇩🇪",
      },
      away: {
        name: "Ivory Coast",
        code: "CIV",
        flag: "🇨🇮",
      },
      venue: "BMO Field, Toronto",
      status: "upcoming",
      score: null,
    },
    {
      id: "m28",
      date: "2026-06-20",
      kickoff: "8:00 PM ET",
      stage: "Group E",
      home: {
        name: "Ecuador",
        code: "ECU",
        flag: "🇪🇨",
      },
      away: {
        name: "Curaçao",
        code: "CUW",
        flag: "🇨🇼",
      },
      venue: "Arrowhead Stadium, Kansas City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m29",
      date: "2026-06-25",
      kickoff: "4:00 PM ET",
      stage: "Group E",
      home: {
        name: "Ecuador",
        code: "ECU",
        flag: "🇪🇨",
      },
      away: {
        name: "Germany",
        code: "GER",
        flag: "🇩🇪",
      },
      venue: "MetLife Stadium, New Jersey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m30",
      date: "2026-06-25",
      kickoff: "4:00 PM ET",
      stage: "Group E",
      home: {
        name: "Curaçao",
        code: "CUW",
        flag: "🇨🇼",
      },
      away: {
        name: "Ivory Coast",
        code: "CIV",
        flag: "🇨🇮",
      },
      venue: "Lincoln Financial Field, Philadelphia",
      status: "upcoming",
      score: null,
    },
    {
      id: "m31",
      date: "2026-06-14",
      kickoff: "4:00 PM ET",
      stage: "Group F",
      home: {
        name: "Netherlands",
        code: "NED",
        flag: "🇳🇱",
      },
      away: {
        name: "Japan",
        code: "JPN",
        flag: "🇯🇵",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m32",
      date: "2026-06-14",
      kickoff: "10:00 PM ET",
      stage: "Group F",
      home: {
        name: "Sweden",
        code: "SWE",
        flag: "🇸🇪",
      },
      away: {
        name: "Tunisia",
        code: "TUN",
        flag: "🇹🇳",
      },
      venue: "Estadio BBVA, Monterrey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m33",
      date: "2026-06-20",
      kickoff: "1:00 PM ET",
      stage: "Group F",
      home: {
        name: "Netherlands",
        code: "NED",
        flag: "🇳🇱",
      },
      away: {
        name: "Sweden",
        code: "SWE",
        flag: "🇸🇪",
      },
      venue: "NRG Stadium, Houston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m34",
      date: "2026-06-20",
      kickoff: "12:00 AM ET",
      stage: "Group F",
      home: {
        name: "Tunisia",
        code: "TUN",
        flag: "🇹🇳",
      },
      away: {
        name: "Japan",
        code: "JPN",
        flag: "🇯🇵",
      },
      venue: "Estadio BBVA, Monterrey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m35",
      date: "2026-06-25",
      kickoff: "7:00 PM ET",
      stage: "Group F",
      home: {
        name: "Japan",
        code: "JPN",
        flag: "🇯🇵",
      },
      away: {
        name: "Sweden",
        code: "SWE",
        flag: "🇸🇪",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m36",
      date: "2026-06-25",
      kickoff: "7:00 PM ET",
      stage: "Group F",
      home: {
        name: "Tunisia",
        code: "TUN",
        flag: "🇹🇳",
      },
      away: {
        name: "Netherlands",
        code: "NED",
        flag: "🇳🇱",
      },
      venue: "Arrowhead Stadium, Kansas City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m37",
      date: "2026-06-15",
      kickoff: "3:00 PM ET",
      stage: "Group G",
      home: {
        name: "Belgium",
        code: "BEL",
        flag: "🇧🇪",
      },
      away: {
        name: "Egypt",
        code: "EGY",
        flag: "🇪🇬",
      },
      venue: "Lumen Field, Seattle",
      status: "upcoming",
      score: null,
    },
    {
      id: "m38",
      date: "2026-06-15",
      kickoff: "9:00 PM ET",
      stage: "Group G",
      home: {
        name: "Iran",
        code: "IRN",
        flag: "🇮🇷",
      },
      away: {
        name: "New Zealand",
        code: "NZL",
        flag: "🇳🇿",
      },
      venue: "SoFi Stadium, Los Angeles",
      status: "upcoming",
      score: null,
    },
    {
      id: "m39",
      date: "2026-06-21",
      kickoff: "3:00 PM ET",
      stage: "Group G",
      home: {
        name: "Belgium",
        code: "BEL",
        flag: "🇧🇪",
      },
      away: {
        name: "Iran",
        code: "IRN",
        flag: "🇮🇷",
      },
      venue: "SoFi Stadium, Los Angeles",
      status: "upcoming",
      score: null,
    },
    {
      id: "m40",
      date: "2026-06-21",
      kickoff: "9:00 PM ET",
      stage: "Group G",
      home: {
        name: "New Zealand",
        code: "NZL",
        flag: "🇳🇿",
      },
      away: {
        name: "Egypt",
        code: "EGY",
        flag: "🇪🇬",
      },
      venue: "BC Place, Vancouver",
      status: "upcoming",
      score: null,
    },
    {
      id: "m41",
      date: "2026-06-26",
      kickoff: "11:00 PM ET",
      stage: "Group G",
      home: {
        name: "Egypt",
        code: "EGY",
        flag: "🇪🇬",
      },
      away: {
        name: "Iran",
        code: "IRN",
        flag: "🇮🇷",
      },
      venue: "Lumen Field, Seattle",
      status: "upcoming",
      score: null,
    },
    {
      id: "m42",
      date: "2026-06-26",
      kickoff: "11:00 PM ET",
      stage: "Group G",
      home: {
        name: "New Zealand",
        code: "NZL",
        flag: "🇳🇿",
      },
      away: {
        name: "Belgium",
        code: "BEL",
        flag: "🇧🇪",
      },
      venue: "BC Place, Vancouver",
      status: "upcoming",
      score: null,
    },
    {
      id: "m43",
      date: "2026-06-15",
      kickoff: "12:00 PM ET",
      stage: "Group H",
      home: {
        name: "Spain",
        code: "ESP",
        flag: "🇪🇸",
      },
      away: {
        name: "Cape Verde",
        code: "CPV",
        flag: "🇨🇻",
      },
      venue: "Mercedes-Benz Stadium, Atlanta",
      status: "upcoming",
      score: null,
    },
    {
      id: "m44",
      date: "2026-06-15",
      kickoff: "6:00 PM ET",
      stage: "Group H",
      home: {
        name: "Saudi Arabia",
        code: "KSA",
        flag: "🇸🇦",
      },
      away: {
        name: "Uruguay",
        code: "URU",
        flag: "🇺🇾",
      },
      venue: "Hard Rock Stadium, Miami",
      status: "upcoming",
      score: null,
    },
    {
      id: "m45",
      date: "2026-06-21",
      kickoff: "12:00 PM ET",
      stage: "Group H",
      home: {
        name: "Spain",
        code: "ESP",
        flag: "🇪🇸",
      },
      away: {
        name: "Saudi Arabia",
        code: "KSA",
        flag: "🇸🇦",
      },
      venue: "Mercedes-Benz Stadium, Atlanta",
      status: "upcoming",
      score: null,
    },
    {
      id: "m46",
      date: "2026-06-21",
      kickoff: "6:00 PM ET",
      stage: "Group H",
      home: {
        name: "Uruguay",
        code: "URU",
        flag: "🇺🇾",
      },
      away: {
        name: "Cape Verde",
        code: "CPV",
        flag: "🇨🇻",
      },
      venue: "Hard Rock Stadium, Miami",
      status: "upcoming",
      score: null,
    },
    {
      id: "m47",
      date: "2026-06-26",
      kickoff: "8:00 PM ET",
      stage: "Group H",
      home: {
        name: "Cape Verde",
        code: "CPV",
        flag: "🇨🇻",
      },
      away: {
        name: "Saudi Arabia",
        code: "KSA",
        flag: "🇸🇦",
      },
      venue: "NRG Stadium, Houston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m48",
      date: "2026-06-26",
      kickoff: "8:00 PM ET",
      stage: "Group H",
      home: {
        name: "Uruguay",
        code: "URU",
        flag: "🇺🇾",
      },
      away: {
        name: "Spain",
        code: "ESP",
        flag: "🇪🇸",
      },
      venue: "Estadio Akron, Guadalajara",
      status: "upcoming",
      score: null,
    },
    {
      id: "m49",
      date: "2026-06-16",
      kickoff: "3:00 PM ET",
      stage: "Group I",
      home: {
        name: "France",
        code: "FRA",
        flag: "🇫🇷",
      },
      away: {
        name: "Senegal",
        code: "SEN",
        flag: "🇸🇳",
      },
      venue: "MetLife Stadium, New Jersey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m50",
      date: "2026-06-16",
      kickoff: "6:00 PM ET",
      stage: "Group I",
      home: {
        name: "Iraq",
        code: "IRQ",
        flag: "🇮🇶",
      },
      away: {
        name: "Norway",
        code: "NOR",
        flag: "🇳🇴",
      },
      venue: "Gillette Stadium, Boston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m51",
      date: "2026-06-22",
      kickoff: "5:00 PM ET",
      stage: "Group I",
      home: {
        name: "France",
        code: "FRA",
        flag: "🇫🇷",
      },
      away: {
        name: "Iraq",
        code: "IRQ",
        flag: "🇮🇶",
      },
      venue: "Lincoln Financial Field, Philadelphia",
      status: "upcoming",
      score: null,
    },
    {
      id: "m52",
      date: "2026-06-22",
      kickoff: "8:00 PM ET",
      stage: "Group I",
      home: {
        name: "Norway",
        code: "NOR",
        flag: "🇳🇴",
      },
      away: {
        name: "Senegal",
        code: "SEN",
        flag: "🇸🇳",
      },
      venue: "MetLife Stadium, New Jersey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m53",
      date: "2026-06-26",
      kickoff: "3:00 PM ET",
      stage: "Group I",
      home: {
        name: "Norway",
        code: "NOR",
        flag: "🇳🇴",
      },
      away: {
        name: "France",
        code: "FRA",
        flag: "🇫🇷",
      },
      venue: "Gillette Stadium, Boston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m54",
      date: "2026-06-26",
      kickoff: "3:00 PM ET",
      stage: "Group I",
      home: {
        name: "Senegal",
        code: "SEN",
        flag: "🇸🇳",
      },
      away: {
        name: "Iraq",
        code: "IRQ",
        flag: "🇮🇶",
      },
      venue: "BMO Field, Toronto",
      status: "upcoming",
      score: null,
    },
    {
      id: "m55",
      date: "2026-06-16",
      kickoff: "9:00 PM ET",
      stage: "Group J",
      home: {
        name: "Argentina",
        code: "ARG",
        flag: "🇦🇷",
      },
      away: {
        name: "Algeria",
        code: "ALG",
        flag: "🇩🇿",
      },
      venue: "Arrowhead Stadium, Kansas City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m56",
      date: "2026-06-16",
      kickoff: "12:00 AM ET",
      stage: "Group J",
      home: {
        name: "Austria",
        code: "AUT",
        flag: "🇦🇹",
      },
      away: {
        name: "Jordan",
        code: "JOR",
        flag: "🇯🇴",
      },
      venue: "Levi's Stadium, San Francisco",
      status: "upcoming",
      score: null,
    },
    {
      id: "m57",
      date: "2026-06-22",
      kickoff: "1:00 PM ET",
      stage: "Group J",
      home: {
        name: "Argentina",
        code: "ARG",
        flag: "🇦🇷",
      },
      away: {
        name: "Austria",
        code: "AUT",
        flag: "🇦🇹",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m58",
      date: "2026-06-22",
      kickoff: "11:00 PM ET",
      stage: "Group J",
      home: {
        name: "Jordan",
        code: "JOR",
        flag: "🇯🇴",
      },
      away: {
        name: "Algeria",
        code: "ALG",
        flag: "🇩🇿",
      },
      venue: "Levi's Stadium, San Francisco",
      status: "upcoming",
      score: null,
    },
    {
      id: "m59",
      date: "2026-06-27",
      kickoff: "10:00 PM ET",
      stage: "Group J",
      home: {
        name: "Algeria",
        code: "ALG",
        flag: "🇩🇿",
      },
      away: {
        name: "Austria",
        code: "AUT",
        flag: "🇦🇹",
      },
      venue: "Arrowhead Stadium, Kansas City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m60",
      date: "2026-06-27",
      kickoff: "10:00 PM ET",
      stage: "Group J",
      home: {
        name: "Jordan",
        code: "JOR",
        flag: "🇯🇴",
      },
      away: {
        name: "Argentina",
        code: "ARG",
        flag: "🇦🇷",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m61",
      date: "2026-06-17",
      kickoff: "1:00 PM ET",
      stage: "Group K",
      home: {
        name: "Portugal",
        code: "POR",
        flag: "🇵🇹",
      },
      away: {
        name: "DR Congo",
        code: "COD",
        flag: "🇨🇩",
      },
      venue: "NRG Stadium, Houston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m62",
      date: "2026-06-17",
      kickoff: "10:00 PM ET",
      stage: "Group K",
      home: {
        name: "Uzbekistan",
        code: "UZB",
        flag: "🇺🇿",
      },
      away: {
        name: "Colombia",
        code: "COL",
        flag: "🇨🇴",
      },
      venue: "Estadio Azteca, Mexico City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m63",
      date: "2026-06-23",
      kickoff: "1:00 PM ET",
      stage: "Group K",
      home: {
        name: "Portugal",
        code: "POR",
        flag: "🇵🇹",
      },
      away: {
        name: "Uzbekistan",
        code: "UZB",
        flag: "🇺🇿",
      },
      venue: "NRG Stadium, Houston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m64",
      date: "2026-06-23",
      kickoff: "10:00 PM ET",
      stage: "Group K",
      home: {
        name: "Colombia",
        code: "COL",
        flag: "🇨🇴",
      },
      away: {
        name: "DR Congo",
        code: "COD",
        flag: "🇨🇩",
      },
      venue: "Estadio Akron, Guadalajara",
      status: "upcoming",
      score: null,
    },
    {
      id: "m65",
      date: "2026-06-27",
      kickoff: "7:30 PM ET",
      stage: "Group K",
      home: {
        name: "Colombia",
        code: "COL",
        flag: "🇨🇴",
      },
      away: {
        name: "Portugal",
        code: "POR",
        flag: "🇵🇹",
      },
      venue: "Hard Rock Stadium, Miami",
      status: "upcoming",
      score: null,
    },
    {
      id: "m66",
      date: "2026-06-27",
      kickoff: "7:30 PM ET",
      stage: "Group K",
      home: {
        name: "DR Congo",
        code: "COD",
        flag: "🇨🇩",
      },
      away: {
        name: "Uzbekistan",
        code: "UZB",
        flag: "🇺🇿",
      },
      venue: "Mercedes-Benz Stadium, Atlanta",
      status: "upcoming",
      score: null,
    },
    {
      id: "m67",
      date: "2026-06-17",
      kickoff: "4:00 PM ET",
      stage: "Group L",
      home: {
        name: "England",
        code: "ENG",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      },
      away: {
        name: "Croatia",
        code: "CRO",
        flag: "🇭🇷",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m68",
      date: "2026-06-17",
      kickoff: "7:00 PM ET",
      stage: "Group L",
      home: {
        name: "Ghana",
        code: "GHA",
        flag: "🇬🇭",
      },
      away: {
        name: "Panama",
        code: "PAN",
        flag: "🇵🇦",
      },
      venue: "BMO Field, Toronto",
      status: "upcoming",
      score: null,
    },
    {
      id: "m69",
      date: "2026-06-23",
      kickoff: "4:00 PM ET",
      stage: "Group L",
      home: {
        name: "England",
        code: "ENG",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      },
      away: {
        name: "Ghana",
        code: "GHA",
        flag: "🇬🇭",
      },
      venue: "Gillette Stadium, Boston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m70",
      date: "2026-06-23",
      kickoff: "7:00 PM ET",
      stage: "Group L",
      home: {
        name: "Panama",
        code: "PAN",
        flag: "🇵🇦",
      },
      away: {
        name: "Croatia",
        code: "CRO",
        flag: "🇭🇷",
      },
      venue: "BMO Field, Toronto",
      status: "upcoming",
      score: null,
    },
    {
      id: "m71",
      date: "2026-06-27",
      kickoff: "5:00 PM ET",
      stage: "Group L",
      home: {
        name: "Panama",
        code: "PAN",
        flag: "🇵🇦",
      },
      away: {
        name: "England",
        code: "ENG",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      },
      venue: "MetLife Stadium, New Jersey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m72",
      date: "2026-06-27",
      kickoff: "5:00 PM ET",
      stage: "Group L",
      home: {
        name: "Croatia",
        code: "CRO",
        flag: "🇭🇷",
      },
      away: {
        name: "Ghana",
        code: "GHA",
        flag: "🇬🇭",
      },
      venue: "Lincoln Financial Field, Philadelphia",
      status: "upcoming",
      score: null,
    },
    {
      id: "m73",
      date: "2026-06-28",
      kickoff: "3:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "A2",
        code: "A2",
        flag: "🏳️",
      },
      away: {
        name: "B2",
        code: "B2",
        flag: "🏳️",
      },
      venue: "SoFi Stadium, Los Angeles",
      status: "upcoming",
      score: null,
    },
    {
      id: "m74",
      date: "2026-06-29",
      kickoff: "4:30 PM ET",
      stage: "Round of 32",
      home: {
        name: "E1",
        code: "E1",
        flag: "🏳️",
      },
      away: {
        name: "3rd",
        code: "3rd",
        flag: "🏳️",
      },
      venue: "Gillette Stadium, Boston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m75",
      date: "2026-06-29",
      kickoff: "9:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "F1",
        code: "F1",
        flag: "🏳️",
      },
      away: {
        name: "C2",
        code: "C2",
        flag: "🏳️",
      },
      venue: "Estadio BBVA, Monterrey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m76",
      date: "2026-06-29",
      kickoff: "1:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "C1",
        code: "C1",
        flag: "🏳️",
      },
      away: {
        name: "F2",
        code: "F2",
        flag: "🏳️",
      },
      venue: "NRG Stadium, Houston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m77",
      date: "2026-06-30",
      kickoff: "5:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "I1",
        code: "I1",
        flag: "🏳️",
      },
      away: {
        name: "3rd",
        code: "3rd",
        flag: "🏳️",
      },
      venue: "MetLife Stadium, New Jersey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m78",
      date: "2026-06-30",
      kickoff: "1:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "E2",
        code: "E2",
        flag: "🏳️",
      },
      away: {
        name: "I2",
        code: "I2",
        flag: "🏳️",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m79",
      date: "2026-06-30",
      kickoff: "9:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "A1",
        code: "A1",
        flag: "🏳️",
      },
      away: {
        name: "3rd",
        code: "3rd",
        flag: "🏳️",
      },
      venue: "Estadio Azteca, Mexico City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m80",
      date: "2026-07-01",
      kickoff: "12:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "L1",
        code: "L1",
        flag: "🏳️",
      },
      away: {
        name: "3rd",
        code: "3rd",
        flag: "🏳️",
      },
      venue: "Mercedes-Benz Stadium, Atlanta",
      status: "upcoming",
      score: null,
    },
    {
      id: "m81",
      date: "2026-07-01",
      kickoff: "8:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "D1",
        code: "D1",
        flag: "🏳️",
      },
      away: {
        name: "3rd",
        code: "3rd",
        flag: "🏳️",
      },
      venue: "Levi's Stadium, San Francisco",
      status: "upcoming",
      score: null,
    },
    {
      id: "m82",
      date: "2026-07-01",
      kickoff: "4:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "G1",
        code: "G1",
        flag: "🏳️",
      },
      away: {
        name: "3rd",
        code: "3rd",
        flag: "🏳️",
      },
      venue: "Lumen Field, Seattle",
      status: "upcoming",
      score: null,
    },
    {
      id: "m83",
      date: "2026-07-02",
      kickoff: "7:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "K2",
        code: "K2",
        flag: "🏳️",
      },
      away: {
        name: "L2",
        code: "L2",
        flag: "🏳️",
      },
      venue: "BMO Field, Toronto",
      status: "upcoming",
      score: null,
    },
    {
      id: "m84",
      date: "2026-07-02",
      kickoff: "3:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "H1",
        code: "H1",
        flag: "🏳️",
      },
      away: {
        name: "J2",
        code: "J2",
        flag: "🏳️",
      },
      venue: "SoFi Stadium, Los Angeles",
      status: "upcoming",
      score: null,
    },
    {
      id: "m85",
      date: "2026-07-02",
      kickoff: "11:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "B1",
        code: "B1",
        flag: "🏳️",
      },
      away: {
        name: "3rd",
        code: "3rd",
        flag: "🏳️",
      },
      venue: "BC Place, Vancouver",
      status: "upcoming",
      score: null,
    },
    {
      id: "m86",
      date: "2026-07-03",
      kickoff: "6:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "J1",
        code: "J1",
        flag: "🏳️",
      },
      away: {
        name: "H2",
        code: "H2",
        flag: "🏳️",
      },
      venue: "Hard Rock Stadium, Miami",
      status: "upcoming",
      score: null,
    },
    {
      id: "m87",
      date: "2026-07-03",
      kickoff: "9:30 PM ET",
      stage: "Round of 32",
      home: {
        name: "K1",
        code: "K1",
        flag: "🏳️",
      },
      away: {
        name: "3rd",
        code: "3rd",
        flag: "🏳️",
      },
      venue: "Arrowhead Stadium, Kansas City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m88",
      date: "2026-07-03",
      kickoff: "2:00 PM ET",
      stage: "Round of 32",
      home: {
        name: "D2",
        code: "D2",
        flag: "🏳️",
      },
      away: {
        name: "G2",
        code: "G2",
        flag: "🏳️",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m89",
      date: "2026-07-04",
      kickoff: "5:00 PM ET",
      stage: "Round of 16",
      home: {
        name: "W74",
        code: "W74",
        flag: "🏳️",
      },
      away: {
        name: "W77",
        code: "W77",
        flag: "🏳️",
      },
      venue: "Lincoln Financial Field, Philadelphia",
      status: "upcoming",
      score: null,
    },
    {
      id: "m90",
      date: "2026-07-04",
      kickoff: "1:00 PM ET",
      stage: "Round of 16",
      home: {
        name: "W73",
        code: "W73",
        flag: "🏳️",
      },
      away: {
        name: "W75",
        code: "W75",
        flag: "🏳️",
      },
      venue: "NRG Stadium, Houston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m91",
      date: "2026-07-05",
      kickoff: "4:00 PM ET",
      stage: "Round of 16",
      home: {
        name: "W76",
        code: "W76",
        flag: "🏳️",
      },
      away: {
        name: "W78",
        code: "W78",
        flag: "🏳️",
      },
      venue: "MetLife Stadium, New Jersey",
      status: "upcoming",
      score: null,
    },
    {
      id: "m92",
      date: "2026-07-05",
      kickoff: "8:00 PM ET",
      stage: "Round of 16",
      home: {
        name: "W79",
        code: "W79",
        flag: "🏳️",
      },
      away: {
        name: "W80",
        code: "W80",
        flag: "🏳️",
      },
      venue: "Estadio Azteca, Mexico City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m93",
      date: "2026-07-06",
      kickoff: "3:00 PM ET",
      stage: "Round of 16",
      home: {
        name: "W83",
        code: "W83",
        flag: "🏳️",
      },
      away: {
        name: "W84",
        code: "W84",
        flag: "🏳️",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m94",
      date: "2026-07-06",
      kickoff: "8:00 PM ET",
      stage: "Round of 16",
      home: {
        name: "W81",
        code: "W81",
        flag: "🏳️",
      },
      away: {
        name: "W82",
        code: "W82",
        flag: "🏳️",
      },
      venue: "Lumen Field, Seattle",
      status: "upcoming",
      score: null,
    },
    {
      id: "m95",
      date: "2026-07-07",
      kickoff: "12:00 PM ET",
      stage: "Round of 16",
      home: {
        name: "W86",
        code: "W86",
        flag: "🏳️",
      },
      away: {
        name: "W88",
        code: "W88",
        flag: "🏳️",
      },
      venue: "Mercedes-Benz Stadium, Atlanta",
      status: "upcoming",
      score: null,
    },
    {
      id: "m96",
      date: "2026-07-07",
      kickoff: "4:00 PM ET",
      stage: "Round of 16",
      home: {
        name: "W85",
        code: "W85",
        flag: "🏳️",
      },
      away: {
        name: "W87",
        code: "W87",
        flag: "🏳️",
      },
      venue: "BC Place, Vancouver",
      status: "upcoming",
      score: null,
    },
    {
      id: "m97",
      date: "2026-07-09",
      kickoff: "4:00 PM ET",
      stage: "Quarterfinal",
      home: {
        name: "W89",
        code: "W89",
        flag: "🏳️",
      },
      away: {
        name: "W90",
        code: "W90",
        flag: "🏳️",
      },
      venue: "Gillette Stadium, Boston",
      status: "upcoming",
      score: null,
    },
    {
      id: "m98",
      date: "2026-07-10",
      kickoff: "3:00 PM ET",
      stage: "Quarterfinal",
      home: {
        name: "W93",
        code: "W93",
        flag: "🏳️",
      },
      away: {
        name: "W94",
        code: "W94",
        flag: "🏳️",
      },
      venue: "SoFi Stadium, Los Angeles",
      status: "upcoming",
      score: null,
    },
    {
      id: "m99",
      date: "2026-07-11",
      kickoff: "5:00 PM ET",
      stage: "Quarterfinal",
      home: {
        name: "W91",
        code: "W91",
        flag: "🏳️",
      },
      away: {
        name: "W92",
        code: "W92",
        flag: "🏳️",
      },
      venue: "Hard Rock Stadium, Miami",
      status: "upcoming",
      score: null,
    },
    {
      id: "m100",
      date: "2026-07-11",
      kickoff: "9:00 PM ET",
      stage: "Quarterfinal",
      home: {
        name: "W95",
        code: "W95",
        flag: "🏳️",
      },
      away: {
        name: "W96",
        code: "W96",
        flag: "🏳️",
      },
      venue: "Arrowhead Stadium, Kansas City",
      status: "upcoming",
      score: null,
    },
    {
      id: "m101",
      date: "2026-07-14",
      kickoff: "3:00 PM ET",
      stage: "Semifinal",
      home: {
        name: "W97",
        code: "W97",
        flag: "🏳️",
      },
      away: {
        name: "W98",
        code: "W98",
        flag: "🏳️",
      },
      venue: "AT&T Stadium, Dallas",
      status: "upcoming",
      score: null,
    },
    {
      id: "m102",
      date: "2026-07-15",
      kickoff: "3:00 PM ET",
      stage: "Semifinal",
      home: {
        name: "W99",
        code: "W99",
        flag: "🏳️",
      },
      away: {
        name: "W100",
        code: "W100",
        flag: "🏳️",
      },
      venue: "Mercedes-Benz Stadium, Atlanta",
      status: "upcoming",
      score: null,
    },
    {
      id: "m103",
      date: "2026-07-18",
      kickoff: "5:00 PM ET",
      stage: "Third Place",
      home: {
        name: "L101",
        code: "L101",
        flag: "🏳️",
      },
      away: {
        name: "L102",
        code: "L102",
        flag: "🏳️",
      },
      venue: "Hard Rock Stadium, Miami",
      status: "upcoming",
      score: null,
    },
    {
      id: "m104",
      date: "2026-07-19",
      kickoff: "3:00 PM ET",
      stage: "Final 🏆",
      home: {
        name: "W101",
        code: "W101",
        flag: "🏳️",
      },
      away: {
        name: "W102",
        code: "W102",
        flag: "🏳️",
      },
      venue: "MetLife Stadium, New Jersey",
      status: "upcoming",
      score: null,
    },
  ],
  social: [
    {
      "id": "s137",
      "topic": "🧤 Neuer at 40 — 'Respect Your Elders' Takes Over Keeper Twitter",
      "category": "memes",
      "volume": "🔥🔥🔥🔥",
      "sentiment": "positive",
      "summary": "Manuel Neuer's recall at 40 has set off a wave of affectionate 'grandpa in goal' and 'respect your elders' content. Fans are splicing his sweeper-keeper highlights with captions about a fifth World Cup, while others meme the age gap with his Musiala/Wirtz teammates. Largely warm and cross-generational — a clean lane for legacy/longevity-coded creative without wading into selection debates 🧤",
      "sampleQuote": "\"Neuer at 40 still has a higher top speed than my entire fantasy backline.\"",
      "quotes": [
        {
          "platform": "X",
          "text": "40 years old and still rushing out past the halfway line. never change king"
        },
        {
          "platform": "TikTok",
          "text": "POV: the keeper is older than half the group chat watching the game"
        },
        {
          "platform": "Reddit",
          "text": "r/soccer collectively tipping its cap to Neuer one more time"
        }
      ],
      "platforms": [
        "X",
        "TikTok",
        "Reddit"
      ],
      "sourceUrl": "https://www.bundesliga.com/en/bundesliga/news/germany-squad-world-cup-2026-manuel-neuer-nagelsmann-37487",
      "timestamp": "2026-06-06T12:00:00Z"
    },
    {
      "id": "s136",
      "topic": "🇨🇼 Curaçao Mania — Smallest Nation Ever at a World Cup Wins the Internet",
      "category": "fandom",
      "volume": "🔥🔥🔥🔥",
      "sentiment": "positive",
      "summary": "Curaçao's arrival as the smallest nation by population ever to reach a World Cup has made them everyone's adopted second team. Underdog edits, 'population smaller than the stadium' stats and Caribbean-pride content are spreading fast ahead of their June 14 opener vs Germany. A feel-good, low-risk bandwagon — great for underdog/David-vs-Goliath storytelling that travels across every market 🐦",
      "sampleQuote": "\"Curaçao has fewer people than show up to a single match and they made the World Cup. football is beautiful.\"",
      "quotes": [
        {
          "platform": "X",
          "text": "everyone's second team is Curaçao now, i don't make the rules"
        },
        {
          "platform": "TikTok",
          "text": "the Curaçao squad celebrating qualification is the best video on here"
        },
        {
          "platform": "Reddit",
          "text": "drawing Germany first is brutal but let them cook"
        }
      ],
      "platforms": [
        "X",
        "TikTok",
        "Reddit"
      ],
      "sourceUrl": "https://www.aljazeera.com/sports/2026/5/31/germany-world-cup-2026-team-preview-players-to-watch-group-and-squad-list",
      "timestamp": "2026-06-06T15:00:00Z"
    },
    {
      "id": "s135",
      "topic": "🌡️ 'It's Going to Cook' — Summer-Heat Discourse Heats Up Pre-Kickoff",
      "category": "game",
      "volume": "🔥🔥🔥",
      "sentiment": "caution",
      "summary": "As teams acclimatize to North American summer conditions, fans are split between memeing brutal afternoon kickoffs ('3PM in Dallas is a war crime') and genuine concern over player welfare and water breaks. The discourse spans every market and will recur each match day. Useful for hydration/endurance brand angles — keep it playful but acknowledge the real welfare conversation 💦",
      "sampleQuote": "\"A 3pm kickoff in Monterrey in June? They're going to need oxygen tanks on the bench.\"",
      "quotes": [
        {
          "platform": "X",
          "text": "cooling breaks about to be the most important tactic of the tournament"
        },
        {
          "platform": "Reddit",
          "text": "afternoon kickoffs for the TV money, players left to melt. classic"
        },
        {
          "platform": "TikTok",
          "text": "me watching my team play at 1pm local: 🥵"
        }
      ],
      "platforms": [
        "X",
        "Reddit",
        "TikTok"
      ],
      "sourceUrl": "https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-updates-injuries-squads-storylines-as-the-tournament-looms-200000776.html",
      "timestamp": "2026-06-06T17:00:00Z"
    },
    {
      "id": "s134",
      "topic": "🌮 Fan Festival Food & Music — Host Cities Become the Backdrop",
      "category": "food",
      "volume": "🔥🔥🔥",
      "sentiment": "positive",
      "summary": "With official Fan Festivals opening in LA, Boston, NY/NJ and beyond, creators are previewing the food stalls, local-artist lineups and cultural showcases as much as the football. Expect a wave of 'what to eat at the World Cup', host-city guides and street-culture content all summer. A strong non-match lane — pair city-tagged food/music creative with the fan-zone moments rather than the scoreline 🎶",
      "sampleQuote": "\"Going to the Fan Festival for the football, staying for the tacos and the DJ set.\"",
      "quotes": [
        {
          "platform": "TikTok",
          "text": "World Cup food crawl through every host city, who's coming"
        },
        {
          "platform": "IG",
          "text": "the Boston cultural showcase lineup is actually stacked"
        },
        {
          "platform": "X",
          "text": "$10 GA for the LA Fan Fest is the best deal of the summer"
        }
      ],
      "platforms": [
        "TikTok",
        "IG",
        "X"
      ],
      "sourceUrl": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/fifa-fan-festival",
      "timestamp": "2026-06-08T11:00:00Z"
    },
    {
      "id": "s133",
      "topic": "🦁 England Snub Wars — Foden, Palmer & Trent Omissions Reignite the Debate",
      "category": "game",
      "volume": "🔥🔥🔥🔥",
      "sentiment": "neutral",
      "summary": "Tuchel's ruthless 26 — leaving out Phil Foden, Cole Palmer and Trent Alexander-Arnold while handing Jarell Quansah the nod over Harry Maguire — is still fuelling UK debate as the warm-ups roll. 'Best XI left at home' takes, predicted-lineup arguments and Kane-captaincy content dominate English feeds. High-engagement but spicy — pick a lane carefully; the omissions drive more conversation than the inclusions 🦁",
      "sampleQuote": "\"You could build a genuine knockout-round team out of the players England left at home.\"",
      "quotes": [
        {
          "platform": "X",
          "text": "no Foden, no Palmer, no Trent... bold from Tuchel or mad?"
        },
        {
          "platform": "Reddit",
          "text": "Quansah over Maguire is the call nobody had on their bingo card"
        },
        {
          "platform": "TikTok",
          "text": "ranking every player England snubbed, part 1"
        }
      ],
      "platforms": [
        "X",
        "Reddit",
        "TikTok"
      ],
      "sourceUrl": "https://www.espn.com/soccer/story/_/id/48823863/meet-england-2026-world-cup-squad-26-players-picked-thomas-tuchel-why",
      "timestamp": "2026-06-07T09:00:00Z"
    },
    {
      "id": "s132",
      "topic": "🏟️ Azteca Trilogy — 1970, 1986 & Now 2026 Opening-Day Nostalgia",
      "category": "fandom",
      "volume": "🔥🔥🔥",
      "sentiment": "positive",
      "summary": "As the Estadio Azteca prepares to become the first stadium to host three World Cup openers, football-history content is surging: Pelé in 1970, Maradona's 1986, and now 2026 stitched into 'hallowed ground' edits. Mexican pride and global ground-nostalgia overlap here. A rich heritage lane for opening-day creative — lean on the stadium's mythology, not just the Mexico–South Africa matchup 🏟️",
      "sampleQuote": "\"Pelé, Maradona, and now whoever writes the next chapter. The Azteca has seen it all.\"",
      "quotes": [
        {
          "platform": "X",
          "text": "three World Cup openers at one stadium. the Azteca is sacred ground"
        },
        {
          "platform": "IG",
          "text": "1970 / 1986 / 2026 — same cathedral, three generations"
        },
        {
          "platform": "Reddit",
          "text": "imagine the noise in there on Thursday"
        }
      ],
      "platforms": [
        "X",
        "IG",
        "Reddit"
      ],
      "sourceUrl": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/estadio-azteca-mexico-city-host-opening-match-world-cup-2026",
      "timestamp": "2026-06-08T10:00:00Z"
    },
    {
      "id": "s130",
      "topic": "🐐 Messi's Sixth & Final World Cup — 'The Last Dance' Takes Over Feeds",
      "category": "fandom",
      "volume": "🔥🔥🔥🔥🔥",
      "sentiment": "positive",
      "summary": "With Argentina's squad confirmed and Messi set for a record sixth World Cup, 'Last Dance' nostalgia content is dominating fan feeds. Edits of 2022 Lusail set to emotional audio, 'watch him one more time' captions, and cross-generational 'I saw his first, now his last' posts are the meta. Huge opportunity for legacy/farewell-coded creative — keep it about the football, not the GOAT debate. Skews older-millennial and global 🐐",
      "sampleQuote": "\"Telling my kids I got to watch the best ever play his last World Cup.\"",
      "quotes": [
        {
          "platform": "X",
          "text": "Six World Cups. Let that sink in. We are not watching this again."
        },
        {
          "platform": "TikTok",
          "text": "the last dance edits are going to destroy me all summer"
        },
        {
          "platform": "Reddit",
          "text": "r/soccer agreeing on something for once: enjoy Messi while he's here"
        },
        {
          "platform": "IG",
          "text": "saw his first WC in 2006, watching his last in 2026. football is time travel"
        }
      ],
      "platforms": [
        "X",
        "TikTok",
        "Reddit",
        "IG"
      ],
      "sourceUrl": "https://sports.yahoo.com/soccer/article/every-2026-world-cup-squad-announced-so-far--and-when-teams-will-reveal-their-rosters-170018776.html",
      "timestamp": "2026-05-27T10:00:00Z"
    },
    {
      "id": "s131",
      "topic": "🇺🇸 Pochettino's 26 Drops — USMNT Snub Debate Erupts on Home Soil",
      "category": "game",
      "volume": "🔥🔥🔥🔥",
      "sentiment": "neutral",
      "summary": "The USMNT final-squad reveal at Pier 17 lit up American soccer feeds with the usual snub discourse — who's in, who's robbed, and whether Pochettino's calls hint at his opening XI. Hot-take threads, tier lists, and 'this is the guy who decides our summer' edits are everywhere. Engagement is high but sentiment is split; keep reactive content celebratory rather than picking sides 🇺🇸",
      "sampleQuote": "\"This roster is either genius or a disaster and there is no in between.\"",
      "quotes": [
        {
          "platform": "Reddit",
          "text": "r/ussoccer megathread already at 6k comments, everyone's a selector today"
        },
        {
          "platform": "X",
          "text": "Pochettino looked at the depth chart and chose violence"
        },
        {
          "platform": "TikTok",
          "text": "POV: your guy got snubbed and now you're emotionally invested in spite"
        }
      ],
      "platforms": [
        "Reddit",
        "X",
        "TikTok"
      ],
      "sourceUrl": "https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-tracker-squad-announcements-injuries-key-storylines-and-latest-updates-200000056.html",
      "timestamp": "2026-05-26T22:00:00Z"
    },
    {
      "id": "s132",
      "topic": "🎉 '$10 Fan Fest > $2M Final Ticket' — The Affordable-WC Flex",
      "category": "fandom",
      "volume": "🔥🔥🔥🔥",
      "sentiment": "positive",
      "summary": "Fans are turning the ticket-price gap into a positive flex: LA's $10 Fan Festival GA and free-entry fests in Atlanta, Philly, Kansas City, Mexico City and Vancouver are framed as the 'real' World Cup experience versus inaccessible stadium seats. 'Big screen, free entry, 40,000 strangers screaming' content is outperforming the outrage posts. Strong, brand-safe lane: community, access, and the public-viewing atmosphere 🎉",
      "sampleQuote": "\"$10 fan fest with 40k people beats a $2,000 nosebleed any day of the week.\"",
      "quotes": [
        {
          "platform": "TikTok",
          "text": "the fan fest IS the world cup if you're normal about money"
        },
        {
          "platform": "IG",
          "text": "free entry, face paint, churros, big screen. this is the dream actually"
        },
        {
          "platform": "X",
          "text": "FIFA accidentally made the best part of the WC free"
        }
      ],
      "platforms": [
        "TikTok",
        "IG",
        "X"
      ],
      "sourceUrl": "https://www.aljazeera.com/sports/2026/5/11/fan-festivals-panini-tickets-what-are-fifa-world-cup-fans-talking-about",
      "timestamp": "2026-05-29T11:00:00Z"
    },
    {
      "id": "s133",
      "topic": "🇧🇷 Neymar's Calf Tear Splits Brazil — 'Protect Him' vs Fatalism",
      "category": "game",
      "volume": "🔥🔥🔥",
      "sentiment": "negative",
      "summary": "News of Neymar's grade-2 calf tear sent Brazilian social into its two familiar camps: 'rest him, save him for the knockouts' optimism and 'here we go again' fatalism about his tournament injury record. Memes about the 2-3 week timeline landing right at the group stage are spreading fast. Sensitive topic — avoid dunking; keep any reactive content sympathetic and squad-focused 🇧🇷",
      "sampleQuote": "\"Two to three weeks means he plays game three and we all pretend that was the plan.\"",
      "quotes": [
        {
          "platform": "X",
          "text": "Neymar injury news dropping right on schedule, set your watch to it"
        },
        {
          "platform": "Reddit",
          "text": "r/soccer: genuinely hope he gets fit, the tournament's better with him in it"
        }
      ],
      "platforms": [
        "X",
        "Reddit"
      ],
      "sourceUrl": "https://sports.yahoo.com/soccer/live/2026-world-cup-news-live-tracker-squad-announcements-injuries-key-storylines-and-latest-updates-200000056.html",
      "timestamp": "2026-05-28T17:00:00Z"
    },
    {
      "id": "s134",
      "topic": "📸 Squad-Reveal Season — Federation Graphics Are the Content Format",
      "category": "memes",
      "volume": "🔥🔥🔥",
      "sentiment": "positive",
      "summary": "With a dozen nations dropping final 26s in a single week, the federation squad-reveal graphic has become the dominant creative format — and fans rate the designs as hard as the selections. 'Whoever did that reveal deserves a raise' and 'best/worst squad drop' threads are everywhere. Easy, brand-safe participation lane: react to the design trend, run a 'rate the reveal' format, lean into motion graphics 📸",
      "sampleQuote": "\"I don't even care about the players, I care that this squad announcement goes hard.\"",
      "quotes": [
        {
          "platform": "X",
          "text": "the real World Cup is which federation has the best graphic designer"
        },
        {
          "platform": "IG",
          "text": "squad reveal carousels are the new kit reveals, I don't make the rules"
        },
        {
          "platform": "TikTok",
          "text": "rating every nation's squad announcement graphic, day 4"
        }
      ],
      "platforms": [
        "X",
        "IG",
        "TikTok"
      ],
      "sourceUrl": "https://www.skysports.com/football/news/11095/13543070/world-cup-2026-squad-lists-england-scotland-brazil-usa-spain-france-germany-netherlands-argentina-portugal-and-more",
      "timestamp": "2026-05-27T13:00:00Z"
    }
  ],
  assets: [],
};
